version: 0.2

phases:
  install:
    commands:
      - cd cdk-app-8947486
      - npm install -g aws-cdk
      - npm install
  build:
    commands:
      - npm run build
      - npx cdk synth

artifacts:
  base-directory: cdk-app-8947486/cdk.out
  files:
    - CdkApp8947486Stack.template.json
